import type { LucideProps } from 'lucide-react';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Calculator,
  Calendar,
  Car,
  Check,
  CheckCheck,
  ChevronRight,
  CircleCheck,
  Clipboard,
  Clock,
  Cog,
  Database,
  DatabaseZap,
  FilePlus,
  FileText,
  Filter,
  Home,
  Hourglass,
  Inbox,
  Info,
  Link2,
  List,
  Lock,
  Mail,
  MailOpen,
  Menu,
  MessageSquare,
  Pencil,
  Plus,
  Receipt,
  RefreshCw,
  Save,
  Search,
  Shield,
  ShieldCheck,
  Sparkles,
  Table,
  Trash2,
  TrendingUp,
  Unlock,
  Upload,
  Users,
  X,
} from 'lucide-react';

const ICONS = {
  home: Home,
  receipt: Receipt,
  database: Database,
  'database-zap': DatabaseZap,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  plus: Plus,
  'file-plus': FilePlus,
  'file-text': FileText,
  search: Search,
  x: X,
  check: Check,
  'circle-check': CircleCheck,
  'check-check': CheckCheck,
  link: Link2,
  sparkles: Sparkles,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  calculator: Calculator,
  shield: Shield,
  'shield-check': ShieldCheck,
  lock: Lock,
  unlock: Unlock,
  save: Save,
  mail: Mail,
  'mail-open': MailOpen,
  pencil: Pencil,
  trash: Trash2,
  refresh: RefreshCw,
  upload: Upload,
  clipboard: Clipboard,
  filter: Filter,
  table: Table,
  inbox: Inbox,
  clock: Clock,
  calendar: Calendar,
  car: Car,
  'trending-up': TrendingUp,
  'message-square': MessageSquare,
  list: List,
  menu: Menu,
  users: Users,
  settings: Cog,
  info: Info,
  hourglass: Hourglass,
  'chevron-right': ChevronRight,
} as const;

export type LeonIconName = keyof typeof ICONS;

type LeonIconProps = Omit<LucideProps, 'ref'> & {
  name: LeonIconName;
};

export function LeonIcon({ name, size = 16, strokeWidth = 1.75, className, ...props }: LeonIconProps) {
  const Icon = ICONS[name];
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden {...props} />;
}
